repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # MyPy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [
          types-beautifulsoup4,
          types-requests,
          pydantic,
          litellm,
        ]
        args: [--strict, --ignore-missing-imports]
        files: ^src/

  # Built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Security checks
  # Temporarily disabled due to pbr dependency issues
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.8
#    hooks:
#      - id: bandit
#        name: bandit
#        description: "Bandit is designed to find common security issues in Python code."
#        entry: bandit
#        language: python
#        types: [python]
#        require_serial: false
#        additional_dependencies: ["bandit[toml]"]

  # Conventional commit messages
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# Global settings
default_stages: [pre-commit]
fail_fast: false
